version: "3.9"

services:
  weather:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "${VIRTUAL_PORT}"
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: net-nginx-proxy